describe('methods', function () {
  require('./plain/')
  require('./flatten/')
  require('./convert/')
  require('./each/')
  require('./filter/')
  require('./find/')
  require('./get/')
  require('./keys/')
  require('./lookdown/')
  require('./lookup/')
  require('./map/')
  require('./setwithpath/')
  require('./tostring/')
})
